# Generated by Django 6.0.2 on 2026-02-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField()),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('issuedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('issuedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
