# Generated by Django 6.0.2 on 2026-02-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cityName',
            field=models.CharField(default='Jalandhar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='countryName',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
