# Generated by Django 6.0.2 on 2026-02-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_cityname_event_countryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bannerUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
